/*global define */
define(function () {
    'use strict';

    return {
        GRIDLAYOUT  : 'grid',
        STRING      : 'string',
        PROPERTY	: 'property',
        MOZ			: '-moz-',
        MS			: '-ms-',
        OPERA		: '-o-',
        WEBKIT		: '-webkit-',
        SPACE		: ' ',
        PERIOD		: '.',
        COLON		: ':',
        SEMICOL		: ';',
        OPEN_CURLY  : '{',
        CLOSE_CURLY : '}',
        HYPHEN		: '-',
        EMPTY		: '',
        AUTO		: 'auto',
        NONE		: 'none',
        DISPLAY		: 'display',
        POSITION	: 'position',
        RELATIVE	: 'relative',
        STATIC		: 'static',
        ABSOLUTE	: 'absolute',
        WIDTH		: 'width',
        HEIGHT		: 'height',
        PADDING		: 'padding',
        MARGIN		: 'margin',
        BORDER		: 'border',
        STYLE		: '-style',
        TOP			: 'top',
        BOTTOM		: 'bottom',
        LEFT		: 'left',
        RIGHT		: 'right',
        MIN			: 'min-',
        MAX			: 'max-',
        PX			: 'px',
        EM			: 'em',
        PERCENT		: '%',
        REM			: 'rem',
        FR			: 'fr',
        CONTENTBOX	: 'content-box',
        PADDINGBOX	: 'padding-box',
        STRETCH		: 'stretch',
        // properties, etc.
        GRID				: 'grid',
        INLINEGRID			: 'inline-grid',
        GRIDCOLUMNS			: 'grid-columns',
        GRIDCOLUMN			: 'grid-column',
        GRIDCOLUMNSPAN		: 'grid-column-span',
        GRIDCOLUMNALIGN		: 'grid-column-align',
        GRIDROWS			: 'grid-rows',
        GRIDROW				: 'grid-row',
        GRIDROWSPAN			: 'grid-row-span',
        GRIDROWALIGN		: 'grid-row-align',
        BOXSIZING			: 'box-sizing',
        BLOCKPROGRESSION	: 'block-progression',
        precision					: 0, // decimal places
        agentTruncatesLayoutLengths: true,
        regexSpaces: /\s+/
    };
});